import { Routes } from '@angular/router'

import { HomeComponent } from './pages/home/home.component'
import { LiturgicalCalendarComponent } from './pages/liturgical-calendar/liturgical-calendar.component'
import { PrayersComponent } from './pages/prayers/prayers.component'
import { LectioDivinaComponent } from './pages/lectio-divina/lectio-divina.component'
import { NewLectioComponent } from './pages/new-lectio/new-lectio.component'
import { MoreInfoComponent } from './pages/more-info/more-info.component'
import { NotFoundComponent } from './pages/not-found/not-found.component'
import { ExaminationConscienceComponent } from './pages/examination-conscience/examination-conscience.component'
import { MissalComponent } from './pages/missal/missal.component'
import { BlogComponent } from './pages/blog/blog.component'
import { NewBlogPostComponent } from './pages/new-blog-post/new-blog-post.component'
import { BlogPostComponent } from './pages/blog-post/blog-post.component'
import { ApiComponent } from './pages/api/api.component'
import { AboutComponent } from './pages/about/about.component'
import { DocsComponent } from './pages/docs/docs.component'
import { NewBreviaryComponent } from './pages/new-breviary/new-breviary.component'
import { BreviaryComponent } from './pages/breviary/breviary.component'
import { SaintComponent } from './pages/saint/saint.component'

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'ano-liturgico', component: LiturgicalCalendarComponent },
    { path: 'oracoes', component: PrayersComponent },
    { path: 'lectio-divina', component: LectioDivinaComponent },
    { path: 'nova-lectio', component: NewLectioComponent },
    { path: 'mais', component: MoreInfoComponent },
    { path: 'exame-de-consciencia', component: ExaminationConscienceComponent },
    { path: 'missal', component: MissalComponent },
    { path: 'liturgia-das-horas', component: BreviaryComponent },
    { path: 'blog', component: BlogComponent },
    { path: 'documentos-magisteriais', component: DocsComponent },
    { path: 'blog/:slug', component: BlogPostComponent },
    { path: 'novo-post', component: NewBlogPostComponent },
    { path: 'novo-oficio', component: NewBreviaryComponent },
    { path: 'api', component: ApiComponent },
    { path: 'sobre', component: AboutComponent },
    { path: 'santo/:id', component: SaintComponent },
    { path: '404', component: NotFoundComponent },
    { path: '**', redirectTo: '/404' }
]